@extends('layout')

@section('styles')
    <link rel="stylesheet" href="{{ asset('css/find-job-create.css') }}">
@endsection

@section('content')
    <div class="container">
        <header>
            <h2>
                Create a Job
            </h2>
            <p>Post a job to find a specialist</p>
        </header>

        {{-- Modify it later so it redirect to Employer Jobs Posted Page --}}
        <form method="POST" action="/employer/jobs/store-job-data">
            @csrf
            <!-- CSRF : https://laravel.com/docs/10.x/csrf -->
            {{-- Tittle --}}
            <div class="form-input-container">
                <label for="title">Job Title</label>
                <input type="text" name="title" value="{{ old('title') }}" />

                @error('title')
                    {{-- $message variable is dynamically generated by Laravel based on the 
                    validation error that occurred for the given input field. --}}
                    <p class="error-message">{{ $message }}</p>
                @enderror
            </div>

            {{-- State --}}
            <div class="form-input-container">
                <label for="state">State</label>
                <select name="state" id="state">
                    <option value=""></option>
                    <option value="Johor" {{ old('state') == 'Johor' ? 'selected' : '' }}>Johor</option>
                    <option value="Kedah" {{ old('state') == 'Kedah' ? 'selected' : '' }}>Kedah</option>
                    <option value="Kuala Lumpur" {{ old('state') == 'Kuala Lumpur' ? 'selected' : '' }}>Kuala Lumpur
                    </option>
                    <option value="Labuan" {{ old('state') == 'Labuan' ? 'selected' : '' }}>Labuan</option>
                    <option value="Melaka" {{ old('state') == 'Melaka' ? 'selected' : '' }}>Melaka</option>
                    <option value="Negeri Sembilan" {{ old('state') == 'Negeri Sembilan' ? 'selected' : '' }}>Negeri
                        Sembilan</option>
                    <option value="Pahang" {{ old('state') == 'Pahang' ? 'selected' : '' }}>Pahang</option>
                    <option value="Penang" {{ old('state') == 'Penang' ? 'selected' : '' }}>Penang</option>
                    <option value="Perak" {{ old('state') == 'Perak' ? 'selected' : '' }}>Perak</option>
                    <option value="Perlis" {{ old('state') == 'Perlis' ? 'selected' : '' }}>Perlis</option>
                    <option value="Putrajaya" {{ old('state') == 'Putrajaya' ? 'selected' : '' }}>Putrajaya</option>
                    <option value="Sabah" {{ old('state') == 'Sabah' ? 'selected' : '' }}>Sabah</option>
                    <option value="Sarawak" {{ old('state') == 'Sarawak' ? 'selected' : '' }}>Sarawak</option>
                    <option value="Selangor" {{ old('state') == 'Selangor' ? 'selected' : '' }}>Selangor</option>
                    <option value="Terengganu" {{ old('state') == 'Terengganu' ? 'selected' : '' }}>Terengganu</option>
                    <option value="Others" {{ old('state') == 'Others' ? 'selected' : '' }}>Others</option>
                </select>

                @error('state')
                    {{-- $message variable is dynamically generated by Laravel based on the 
            validation error that occurred for the given input field. --}}
                    <p class="error-message">{{ $message }}</p>
                @enderror
            </div>


            {{-- Description --}}
            <div class="form-input-container">
                <label for="description">Job Description</label>
                <textarea name="description" rows="10" placeholder="Include tasks, requirements, salary, etc">{{ old('description') }}</textarea>

                @error('description')
                    {{-- $message variable is dynamically generated by Laravel based on the validation error that occurred for the given input field. --}}
                    <p class="error-message">{{ $message }}</p>
                @enderror
            </div>


            {{-- Category --}}
            <div class="form-input-container">
                <label for="category">Category</label>
                <select name="category" id="category">
                    <option value=""></option>
                    <option value="Accounting & Consulting" @if (old('category') === 'Accounting & Consulting') selected @endif>Accounting &
                        Consulting</option>
                    <option value="Admin Support" @if (old('category') === 'Admin Support') selected @endif>Admin Support</option>
                    <option value="Customer Service" @if (old('category') === 'Customer Service') selected @endif>Customer Service
                    </option>
                    <option value="Data Science & Analytics" @if (old('category') === 'Data Science & Analytics') selected @endif>Data Science
                        & Analytics</option>
                    <option value="Design & Creative" @if (old('category') === 'Design & Creative') selected @endif>Design & Creative
                    </option>
                    <option value="Engineering & Architecture" @if (old('category') === 'Engineering & Architecture') selected @endif>Engineering
                        & Architecture</option>
                    <option value="IT & Networking" @if (old('category') === 'IT & Networking') selected @endif>IT & Networking
                    </option>
                    <option value="Legal" @if (old('category') === 'Legal') selected @endif>Legal</option>
                    <option value="Sales & Marketing" @if (old('category') === 'Sales & Marketing') selected @endif>Sales & Marketing
                    </option>
                    <option value="Translation" @if (old('category') === 'Translation') selected @endif>Translation</option>
                    <option value="Web/Mobile & Software Dev" @if (old('category') === 'Web/Mobile & Software Dev') selected @endif>Web/Mobile
                        & Software Dev</option>
                    <option value="Writing" @if (old('category') === 'Writing') selected @endif>Writing</option>
                    <option value="Others" @if (old('category') === 'Others') selected @endif>Others</option>
                </select>

                @error('category')
                    {{-- $message variable is dynamically generated by Laravel based on the 
            validation error that occurred for the given input field. --}}
                    <p class="error-message">{{ $message }}</p>
                @enderror
            </div>


            {{-- Job Type --}}
            <div class="form-input-container">
                <label for="type">Job Type</label>
                <select name="type" id="type">
                    <option value=""></option>
                    <option value="Hourly" @if (old('type') === 'Hourly') selected @endif>Hourly</option>
                    <option value="Fixed-Price" @if (old('type') === 'Fixed-Price') selected @endif>Fixed-Price</option>
                </select>

                @error('type')
                    {{-- $message variable is dynamically generated by Laravel based on the 
                validation error that occurred for the given input field. --}}
                    <p class="error-message">{{ $message }}</p>
                @enderror
            </div>


            {{-- Hourly Rate --}}
            <div class="form-input-container">
                <label for="rate">Hourly Rate</label>
                <input type="number" name="rate" placeholder="Example: 5, 10, 100, etc" value="{{ old('rate') }}" />

                @error('rate')
                    {{-- $message variable is dynamically generated by Laravel based on the 
                    validation error that occurred for the given input field. --}}
                    <p class="error-message">{{ $message }}</p>
                @enderror
            </div>


            {{-- Experience Level --}}
            <div class="form-input-container">
                <label for="exp_level">Experience Level</label>
                <select name="exp_level" id="exp_level">
                    <option value=""></option>
                    <option value="Entry" {{ old('exp_level') === 'Entry' ? 'selected' : '' }}>Entry</option>
                    <option value="Intermediate" {{ old('exp_level') === 'Intermediate' ? 'selected' : '' }}>Intermediate
                    </option>
                    <option value="Expert" {{ old('exp_level') === 'Expert' ? 'selected' : '' }}>Expert</option>
                </select>

                @error('exp_level')
                    {{-- $message variable is dynamically generated by Laravel based on the 
            validation error that occurred for the given input field. --}}
                    <p class="error-message">{{ $message }}</p>
                @enderror
            </div>


            {{-- Project Length --}}
            <div class="form-input-container">
                <label for="project_length">Project Length</label>
                <select name="project_length" id="project_length">
                    <option value=""></option>
                    <option value="Less than one month"
                        {{ old('project_length') === 'Less than one month' ? 'selected' : '' }}>Less than one month
                    </option>
                    <option value="1 to 3 months" {{ old('project_length') === '1 to 3 months' ? 'selected' : '' }}>1 to 3
                        months</option>
                    <option value="3 to 6 months" {{ old('project_length') === '3 to 6 months' ? 'selected' : '' }}>3 to 6
                        months</option>
                    <option value="More than 6 months"
                        {{ old('project_length') === 'More than 6 months' ? 'selected' : '' }}>More than 6 months</option>
                </select>

                @error('project_length')
                    {{-- $message variable is dynamically generated by Laravel based on the 
            validation error that occurred for the given input field. --}}
                    <p class="error-message">{{ $message }}</p>
                @enderror
            </div>


            {{-- Skills --}}
            <div class="form-input-container">
                <label for="skills">Skills Required</label>
                <input type="text" name="skills" placeholder="Example: Laravel, Backend, Postgres, etc"
                    value="{{ old('skills') }}" />

                @error('skills')
                    {{-- $message variable is dynamically generated by Laravel based on the 
                    validation error that occurred for the given input field. --}}
                    <p class="error-message">{{ $message }}</p>
                @enderror
            </div>


            {{-- Button --}}
            <div class="form-submit-button-container">
                <button type="submit">
                    Create Job
                </button>

                {{-- Modify it later so it redirect to Employer Jobs Posted Page --}}
                <a href="{{ url()->previous() }}">Back</a>

            </div>
        </form>
    </div>
@endsection

@section('scripts')
@endsection
