@extends('layout')

@section('styles')
    <link rel="stylesheet" href="{{ asset('css/find-job-create.css') }}">
@endsection

@section('content')
    <div class="container">
        <header>
            <h2>
                Give a review
            </h2>
            <p>Share your valuable experience and help others</p>
        </header>

        {{-- Modify it later so it redirect to Employer Jobs Posted Page --}}
        <form method="POST" action="/employer/jobs/{{ $job_id }}/review/store">
            @csrf
            <!-- CSRF : https://laravel.com/docs/10.x/csrf -->

            {{-- Star Ratings --}}
            <div class="form-input-container">
                <label for="rating_value" class="tw-block tw-mb-2 tw-text-sm tw-font-medium tw-text-gray-900">Star
                    Ratings</label>
                <select id="rating_value" name="rating_value"
                    class="tw-border tw-border-gray-300 tw-text-gray-900 tw-text-sm tw-rounded-lg focus:tw-ring-blue-500 focus:tw-border-blue-500 tw-block tw-w-full tw-p-2.5">
                    <option value=""></option>
                    <option value="0" {{ old('rating_value') == '0' ? 'selected' : '' }}>0</option>
                    <option value="1" {{ old('rating_value') == '1' ? 'selected' : '' }}>1</option>
                    <option value="2" {{ old('rating_value') == '2' ? 'selected' : '' }}>2</option>
                    <option value="3" {{ old('rating_value') == '3' ? 'selected' : '' }}>3</option>
                    <option value="4" {{ old('rating_value') == '4' ? 'selected' : '' }}>4</option>
                    <option value="5" {{ old('rating_value') == '5' ? 'selected' : '' }}>5</option>
                </select>

                @error('rating_value')
                    {{-- $message variable is dynamically generated by Laravel based on the 
            validation error that occurred for the given input field. --}}
                    <p class="error-message">{{ $rating_value }}</p>
                @enderror
            </div>

            {{-- Tittle --}}
            <div class="form-input-container">
                <label for="title">Review Title</label>
                <input type="text" name="title" value="{{ old('title') }}" maxlength="40" />
                <p class="tw-mt-1 tw-text-sm tw-text-gray-500" id="file_input_help"></p>
                @error('title')
                    {{-- $message variable is dynamically generated by Laravel based on the 
                    validation error that occurred for the given input field. --}}
                    <p class="error-message">{{ $message }}</p>
                @enderror
            </div>

            {{-- Description --}}
            <div class="form-input-container">
                <label for="description">Review Description</label>
                <textarea name="description" rows="10" maxlength="400">{{ old('description') }}</textarea>

                @error('description')
                    {{-- $message variable is dynamically generated by Laravel based on the validation error that occurred for the given input field. --}}
                    <p class="error-message">{{ $message }}</p>
                @enderror
            </div>

            {{-- Button --}}
            <div class="form-submit-button-container">
                <button type="submit">
                    Submit
                </button>

                {{-- Modify it later so it redirect to Employer Jobs Posted Page --}}
                <a href="{{ url()->previous() }}">Back</a>

            </div>
        </form>
    </div>
@endsection

@section('scripts')
@endsection
